DROP TABLE IF EXISTS drone;
CREATE TABLE drone (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    serial_number VARCHAR(64) NOT NULL UNIQUE,
    model VARCHAR(64),
    status VARCHAR(32) DEFAULT 'OFFLINE', -- ONLINE, OFFLINE, BUSY
    battery_level INT DEFAULT 100,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS orders;
CREATE TABLE orders (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    description VARCHAR(255),
    pickup_lat DOUBLE,
    pickup_lon DOUBLE,
    delivery_lat DOUBLE,
    delivery_lon DOUBLE,
    status VARCHAR(32) DEFAULT 'PENDING', -- PENDING, ASSIGNED, COMPLETED
    drone_id BIGINT,
    version INT DEFAULT 0, -- For optimistic locking
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
